package hu.mnb.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-10-16T20:27:06.968+02:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://www.mnb.hu/webservices/", name = "MNBArfolyamServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface MNBArfolyamServiceSoap {

    @WebResult(name = "GetExchangeRatesResult", targetNamespace = "http://www.mnb.hu/webservices/")
    @RequestWrapper(localName = "GetExchangeRates", targetNamespace = "http://www.mnb.hu/webservices/", className = "hu.mnb.webservices.GetExchangeRates")
    @WebMethod(operationName = "GetExchangeRates", action = "http://www.mnb.hu/webservices/GetExchangeRates")
    @ResponseWrapper(localName = "GetExchangeRatesResponse", targetNamespace = "http://www.mnb.hu/webservices/", className = "hu.mnb.webservices.GetExchangeRatesResponse")
    public java.lang.String getExchangeRates(
        @WebParam(name = "startDate", targetNamespace = "http://www.mnb.hu/webservices/")
        java.lang.String startDate,
        @WebParam(name = "endDate", targetNamespace = "http://www.mnb.hu/webservices/")
        java.lang.String endDate,
        @WebParam(name = "currencyNames", targetNamespace = "http://www.mnb.hu/webservices/")
        java.lang.String currencyNames
    );

    @WebResult(name = "GetCurrenciesResult", targetNamespace = "http://www.mnb.hu/webservices/")
    @RequestWrapper(localName = "GetCurrencies", targetNamespace = "http://www.mnb.hu/webservices/", className = "hu.mnb.webservices.GetCurrencies")
    @WebMethod(operationName = "GetCurrencies", action = "http://www.mnb.hu/webservices/GetCurrencies")
    @ResponseWrapper(localName = "GetCurrenciesResponse", targetNamespace = "http://www.mnb.hu/webservices/", className = "hu.mnb.webservices.GetCurrenciesResponse")
    public java.lang.String getCurrencies();

    @WebResult(name = "GetCurrencyUnitsResult", targetNamespace = "http://www.mnb.hu/webservices/")
    @RequestWrapper(localName = "GetCurrencyUnits", targetNamespace = "http://www.mnb.hu/webservices/", className = "hu.mnb.webservices.GetCurrencyUnits")
    @WebMethod(operationName = "GetCurrencyUnits", action = "http://www.mnb.hu/webservices/GetCurrencyUnits")
    @ResponseWrapper(localName = "GetCurrencyUnitsResponse", targetNamespace = "http://www.mnb.hu/webservices/", className = "hu.mnb.webservices.GetCurrencyUnitsResponse")
    public java.lang.String getCurrencyUnits(
        @WebParam(name = "currencyNames", targetNamespace = "http://www.mnb.hu/webservices/")
        java.lang.String currencyNames
    );

    @WebResult(name = "GetCurrentExchangeRatesResult", targetNamespace = "http://www.mnb.hu/webservices/")
    @RequestWrapper(localName = "GetCurrentExchangeRates", targetNamespace = "http://www.mnb.hu/webservices/", className = "hu.mnb.webservices.GetCurrentExchangeRates")
    @WebMethod(operationName = "GetCurrentExchangeRates", action = "http://www.mnb.hu/webservices/GetCurrentExchangeRates")
    @ResponseWrapper(localName = "GetCurrentExchangeRatesResponse", targetNamespace = "http://www.mnb.hu/webservices/", className = "hu.mnb.webservices.GetCurrentExchangeRatesResponse")
    public java.lang.String getCurrentExchangeRates();

    @WebResult(name = "GetInfoResult", targetNamespace = "http://www.mnb.hu/webservices/")
    @RequestWrapper(localName = "GetInfo", targetNamespace = "http://www.mnb.hu/webservices/", className = "hu.mnb.webservices.GetInfo")
    @WebMethod(operationName = "GetInfo", action = "http://www.mnb.hu/webservices/GetInfo")
    @ResponseWrapper(localName = "GetInfoResponse", targetNamespace = "http://www.mnb.hu/webservices/", className = "hu.mnb.webservices.GetInfoResponse")
    public java.lang.String getInfo();

    @WebResult(name = "GetDateIntervalResult", targetNamespace = "http://www.mnb.hu/webservices/")
    @RequestWrapper(localName = "GetDateInterval", targetNamespace = "http://www.mnb.hu/webservices/", className = "hu.mnb.webservices.GetDateInterval")
    @WebMethod(operationName = "GetDateInterval", action = "http://www.mnb.hu/webservices/GetDateInterval")
    @ResponseWrapper(localName = "GetDateIntervalResponse", targetNamespace = "http://www.mnb.hu/webservices/", className = "hu.mnb.webservices.GetDateIntervalResponse")
    public java.lang.String getDateInterval();
}
