
package hu.mnb.webservices;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-10-16T20:27:06.951+02:00
 * Generated source version: 3.0.1
 * 
 */
public final class MNBArfolyamServiceSoap_MNBArfolyamServiceSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://www.mnb.hu/webservices/", "MNBArfolyamService");

    private MNBArfolyamServiceSoap_MNBArfolyamServiceSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MNBArfolyamService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MNBArfolyamService ss = new MNBArfolyamService(wsdlURL, SERVICE_NAME);
        MNBArfolyamServiceSoap port = ss.getMNBArfolyamServiceSoap12();  
        
        {
        System.out.println("Invoking getExchangeRates...");
        java.lang.String _getExchangeRates_startDate = "";
        java.lang.String _getExchangeRates_endDate = "";
        java.lang.String _getExchangeRates_currencyNames = "";
        java.lang.String _getExchangeRates__return = port.getExchangeRates(_getExchangeRates_startDate, _getExchangeRates_endDate, _getExchangeRates_currencyNames);
        System.out.println("getExchangeRates.result=" + _getExchangeRates__return);


        }
        {
        System.out.println("Invoking getCurrencies...");
        java.lang.String _getCurrencies__return = port.getCurrencies();
        System.out.println("getCurrencies.result=" + _getCurrencies__return);


        }
        {
        System.out.println("Invoking getCurrencyUnits...");
        java.lang.String _getCurrencyUnits_currencyNames = "";
        java.lang.String _getCurrencyUnits__return = port.getCurrencyUnits(_getCurrencyUnits_currencyNames);
        System.out.println("getCurrencyUnits.result=" + _getCurrencyUnits__return);


        }
        {
        System.out.println("Invoking getCurrentExchangeRates...");
        java.lang.String _getCurrentExchangeRates__return = port.getCurrentExchangeRates();
        System.out.println("getCurrentExchangeRates.result=" + _getCurrentExchangeRates__return);


        }
        {
        System.out.println("Invoking getInfo...");
        java.lang.String _getInfo__return = port.getInfo();
        System.out.println("getInfo.result=" + _getInfo__return);


        }
        {
        System.out.println("Invoking getDateInterval...");
        java.lang.String _getDateInterval__return = port.getDateInterval();
        System.out.println("getDateInterval.result=" + _getDateInterval__return);


        }

        System.exit(0);
    }

}
