package org.tempuri;

import hu.mnb.webservices.MNBArfolyamServiceSoap;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2015-09-26T09:22:13.575+02:00
 * Generated source version: 3.1.3
 * 
 */
@WebServiceClient(name = "MNBArfolyamServiceSoapImpl", 
                  wsdlLocation = "http://www.mnb.hu/arfolyamok.asmx?WSDL",
                  targetNamespace = "http://tempuri.org/") 
public class MNBArfolyamServiceSoapImpl extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "MNBArfolyamServiceSoapImpl");
    public final static QName CustomBindingMNBArfolyamServiceSoap = new QName("http://tempuri.org/", "CustomBinding_MNBArfolyamServiceSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://www.mnb.hu/arfolyamok.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MNBArfolyamServiceSoapImpl.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://www.mnb.hu/arfolyamok.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public MNBArfolyamServiceSoapImpl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MNBArfolyamServiceSoapImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MNBArfolyamServiceSoapImpl() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public MNBArfolyamServiceSoapImpl(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MNBArfolyamServiceSoapImpl(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MNBArfolyamServiceSoapImpl(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns MNBArfolyamServiceSoap
     */
    @WebEndpoint(name = "CustomBinding_MNBArfolyamServiceSoap")
    public MNBArfolyamServiceSoap getCustomBindingMNBArfolyamServiceSoap() {
        return super.getPort(CustomBindingMNBArfolyamServiceSoap, MNBArfolyamServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MNBArfolyamServiceSoap
     */
    @WebEndpoint(name = "CustomBinding_MNBArfolyamServiceSoap")
    public MNBArfolyamServiceSoap getCustomBindingMNBArfolyamServiceSoap(WebServiceFeature... features) {
        return super.getPort(CustomBindingMNBArfolyamServiceSoap, MNBArfolyamServiceSoap.class, features);
    }

}
