create table user (
    id bigint generated by default as identity unique,
    username varchar(255) not null,
    password varchar(255) not null,
    primary key (id)
);

insert into User (id, username, password) values (1, 'aacs', 'aacs');

create table article (
    id bigint generated by default as identity unique,
    code varchar(255) not null,
    name varchar(255) not null,
    price bigint not null,
    icon varchar(255) not null,
    primary key (id)
);

insert into article (id, code, name, price, icon) values (1, '1234', 'Sör', 200, 'icon/icon.icon');
insert into article (id, code, name, price, icon) values (2, '234', 'Bor', 1500, 'icon/icon.icon');
insert into article (id, code, name, price, icon) values (3, '34', 'Pálinka', 4000, 'icon/icon.icon');

create table customer (
    id bigint generated by default as identity unique,
    code varchar(255) not null,
    name varchar(255) not null,
    primary key (id)
);

insert into customer (id, code, name) values (1, '0001', 'Ács Ádám');
insert into customer (id, code, name) values (2, '0002', 'Szemők Balázs');